version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: backend-container
    ports:
      - "8000:8000"
    volumes:
      - ./backend/admin-manager:/var/www
    networks:
      - app-network
    environment:
      - DB_CONNECTION=mysql
      - DB_HOST=mysql
      - DB_PORT=3306
      - DB_DATABASE=laravel_db
      - DB_USERNAME=root
      - DB_PASSWORD=root
      - WATCHPACK_POLLING=true
    depends_on:
      - mysql
    command: bash -c "/usr/local/bin/wait-for-it.sh mysql:3306 -- php artisan migrate --force && php artisan serve --host=0.0.0.0 --port=8000"


  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: frontend-container
    ports:
      - "3000:3000"
    depends_on:
      - backend
    volumes:
      - ./frontend/admin-manager/:/admin-manager
      - /admin-manager/node_modules
    environment:
      - WATCHPACK_POLLING=true
    networks:
      - app-network

  mysql:
    image: mysql:8.0
    container_name: mysql-container
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=laravel_db
      - MYSQL_USER=admin
      - MYSQL_PASSWORD=admin
    networks:
      - app-network

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin-container
    ports:
      - "8080:80"
    environment:
      - PMA_HOST=mysql
      - PMA_PORT=3306
    depends_on:
      - mysql
    networks:
      - app-network

volumes:
  mysql-data:

networks:
  app-network:
    driver: bridge
